### ISSUE TITLE
test data is gone

### ISSUE THREAD

**Issue by aromanowski** [g2-bernotas/PS-Plant-Framework#11]
Hi Gytis,
Also wanted to mention that the link to the test data is broken (https://bit.ly/2IBRzKJ) .

All the best,
A

**Comment by g2-bernotas** [comment]
Hi,

Thanks for pointing this out. It seems that the Github repo already had the updated link, but not in the tutorial video description. I have now changed it to: https://bit.ly/39FwnN7

Good luck with it!

Regards,
Gytis
