### ISSUE TITLE
test data link is invalid

### ISSUE THREAD

**Issue by dwolsen** [g2-bernotas/PS-Plant-Framework#4]
Hi, this is a very interesting project, and I would like to try to replicate it. Unfortunately, the "test data" link is no longer valid, or the files have moved. Are you able to repopulate the link with the test data? Thank you!

**Comment by g2-bernotas** [comment]
Hi, thank you for pointing it out. This has now been fixed in the readme document. You can download it from [here](https://bit.ly/39FwnN7), or from the [journal ](https://bit.ly/33ggtpZ) that has accepted this manuscript.

Please re-open this issue if there are any problems.
